collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0
color:
  saturation: 0.2240143
  brandStrength: 0.5591398
  lightness: 0.5143369
  brandColors:
    - '#F3F4F6'
    - '#0F1010'
    - '#636459'
    - '#C5C4B8'
    - '#838173'
  rhythmicContrast: 0.3996416
layout_spectrum: 0
name: mwilming
